# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""
Converts an Ossie YAML semantic model to LookML, the
semantic modeling language for Looker — Google Cloud's semantic layer over
BigQuery. Pure offline conversion — no BigQuery or Looker connection required.

The converter prefers BIGQUERY-dialect expressions and falls back to ANSI_SQL,
mirroring the dialect-selection contract documented in ../README.md.

Mapping summary:
    Ossie semantic_model  -> LookML model (one .lkml document)
    Ossie dataset         -> LookML view (sql_table_name from `source`)
    Ossie field           -> LookML dimension (dimension_group when is_time)
    Ossie metric          -> LookML measure (emitted in the first view)
    Ossie relationship    -> LookML explore + join (sql_on, composite-key aware)

Usage:
    python3 -m ossie_bigquery.converter -i input.yaml -o output.lkml
"""

import argparse
import re
import sys
import warnings

import yaml


SUPPORTED_VERSION = "0.2.0.dev0"

# A bare SQL identifier (gets wrapped as ${TABLE}.<identifier> in LookML).
_SIMPLE_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Default LookML timeframes for a time-based dimension_group.
_DEFAULT_TIMEFRAMES = ["raw", "date", "week", "month", "quarter", "year"]


class OsiConversionError(Exception):
    """Raised when an OSI YAML cannot be converted to LookML."""


def convert_osi_to_lookml(osi_yaml_str):
    """Top-level entry point. Parses OSI YAML, validates, converts, returns a
    LookML document as a string.

    Expects the standard OSI wrapped format::

        version: "0.2.0.dev0"
        semantic_model:
          - name: ...

    Args:
        osi_yaml_str: OSI YAML as a string.

    Returns:
        LookML document string.

    Raises:
        OsiConversionError: If the input cannot be converted.
    """
    root = yaml.safe_load(osi_yaml_str)
    if not isinstance(root, dict):
        raise OsiConversionError("Invalid OSI YAML: expected a mapping at the root")

    version_str = str(root.get("version", ""))
    if version_str != SUPPORTED_VERSION:
        raise OsiConversionError(
            f"Unsupported OSI specification version '{version_str}'. "
            f"Supported: {SUPPORTED_VERSION}"
        )

    semantic_model = root.get("semantic_model")
    if not isinstance(semantic_model, list) or len(semantic_model) == 0:
        raise OsiConversionError(
            "Invalid OSI YAML: 'semantic_model' must be a non-empty list"
        )

    if len(semantic_model) > 1:
        warnings.warn(
            f"OSI YAML contains {len(semantic_model)} semantic models; "
            f"only the first will be converted"
        )

    osi = semantic_model[0]
    if not isinstance(osi, dict):
        raise OsiConversionError(
            "Invalid OSI YAML: 'semantic_model' entries must be mappings"
        )

    return _convert_model(osi)


def _convert_model(osi):
    """Converts the root OSI model dict to a LookML document string."""
    name = osi.get("name")
    if not name:
        raise OsiConversionError("Missing required 'name' field in semantic model")

    blocks = []

    header = [f"# Generated by the OSI -> LookML converter", f"# OSI model: {name}"]
    description = _model_description(osi)
    if description:
        for line in description.splitlines():
            header.append(f"# {line}")
    blocks.append("\n".join(header))

    datasets = osi.get("datasets") or []
    if not datasets:
        warnings.warn(f"Model '{name}' has no datasets; output will be empty")

    # Metrics are model-level in OSI but live inside a view in LookML. Emit them
    # in the first dataset's view and warn, since cross-dataset measures may need
    # to be moved into an explore's scope by hand.
    metrics = osi.get("metrics") or []
    first_dataset_name = datasets[0].get("name") if datasets else None
    if metrics and first_dataset_name:
        warnings.warn(
            f"{len(metrics)} model-level metric(s) emitted into view "
            f"'{first_dataset_name}'; cross-dataset measures may require manual "
            f"placement in an explore"
        )

    for ds in datasets:
        ds_metrics = metrics if ds.get("name") == first_dataset_name else None
        blocks.append(_convert_dataset(ds, ds_metrics))

    relationships = osi.get("relationships") or []
    explores = _convert_relationships(relationships, datasets)
    if explores:
        blocks.append(explores)

    _warn_dropped_fields(osi, "model")

    return "\n\n".join(b for b in blocks if b) + "\n"


def _model_description(osi):
    """Combines `description` and a string `ai_context.instructions` into a
    human-readable description for the model header."""
    description = osi.get("description") or ""
    ai_context = osi.get("ai_context")
    if isinstance(ai_context, str) and ai_context:
        description = f"{description}\n{ai_context}".strip()
    elif isinstance(ai_context, dict):
        instructions = ai_context.get("instructions")
        if isinstance(instructions, str) and instructions:
            description = f"{description}\n{instructions}".strip()
    return description


def _convert_dataset(dataset, metrics):
    """Converts an OSI dataset to a LookML `view` block. `metrics` is an
    optional list of model-level metrics to emit as measures in this view."""
    name = dataset.get("name")
    if not name:
        raise OsiConversionError("Missing required 'name' field in dataset")

    lines = [f"view: {name} {{"]

    source = dataset.get("source")
    table_clause = _convert_source(source, name)
    if table_clause:
        lines.append(_indent(table_clause, 1))
        lines.append("")

    description = _entity_description(dataset)
    if description:
        lines.append(_indent(f'label: "{_escape(name)}"', 1))

    fields = dataset.get("fields") or []
    for field in fields:
        block = _convert_field(field)
        if block:
            lines.append(_indent(block, 1))
            lines.append("")

    for metric in metrics or []:
        block = _convert_metric(metric)
        if block:
            lines.append(_indent(block, 1))
            lines.append("")

    # Trim a trailing blank line before the closing brace.
    while len(lines) > 1 and lines[-1] == "":
        lines.pop()
    lines.append("}")

    _warn_dropped_fields(dataset, f"dataset '{name}'")

    return "\n".join(lines)


def _convert_field(field):
    """Converts an OSI field to a LookML dimension or dimension_group block."""
    name = field.get("name")
    if not name:
        raise OsiConversionError("Missing required 'name' in field")

    expr = _extract_expression(field.get("expression"), name)
    if expr is None:
        return None

    sql = _to_lookml_sql(expr, name)
    is_time = _is_time_dimension(field)
    description = _entity_description(field)

    if is_time:
        lines = [f"dimension_group: {_strip_time_suffix(name)} {{"]
        lines.append(_indent("type: time", 1))
        timeframes = ", ".join(_DEFAULT_TIMEFRAMES)
        lines.append(_indent(f"timeframes: [{timeframes}]", 1))
        lines.append(_indent(f"sql: {sql} ;;", 1))
        if description:
            lines.append(_indent(f'description: "{_escape(description)}"', 1))
        lines.append("}")
        return "\n".join(lines)

    lines = [f"dimension: {name} {{"]
    # OSI fields carry no data type, so default to string. Numeric/keyed fields
    # may need refinement after generation.
    lines.append(_indent("type: string", 1))
    lines.append(_indent(f"sql: {sql} ;;", 1))
    if description:
        lines.append(_indent(f'description: "{_escape(description)}"', 1))
    lines.append("}")
    return "\n".join(lines)


def _convert_metric(metric):
    """Converts an OSI metric to a LookML measure block."""
    name = metric.get("name")
    if not name:
        raise OsiConversionError("Missing required 'name' in metric")

    expr = _extract_expression(metric.get("expression"), name)
    if expr is None:
        return None

    lines = [f"measure: {name} {{"]
    # Aggregate type is not recoverable from the raw expression, so use the
    # generic numeric measure with the expression supplied verbatim.
    lines.append(_indent("type: number", 1))
    lines.append(_indent(f"sql: {expr} ;;", 1))
    description = _entity_description(metric)
    if description:
        lines.append(_indent(f'description: "{_escape(description)}"', 1))
    lines.append("}")
    return "\n".join(lines)


def _convert_relationships(relationships, datasets):
    """Converts OSI relationships to LookML explore/join blocks, grouped by the
    `from` (many-side) dataset."""
    if not relationships:
        return ""

    dataset_names = {d.get("name") for d in datasets if d.get("name")}

    by_base = {}
    for rel in relationships:
        rel_name = rel.get("name")
        if not rel_name:
            raise OsiConversionError("Missing required 'name' field in relationship")

        from_ds = rel.get("from")
        to_ds = rel.get("to")
        if not from_ds or not to_ds:
            raise OsiConversionError(
                f"Relationship '{rel_name}': both 'from' and 'to' are required"
            )
        if dataset_names and from_ds not in dataset_names:
            warnings.warn(
                f"Relationship '{rel_name}': 'from' dataset '{from_ds}' is not "
                f"defined in the model"
            )
        if dataset_names and to_ds not in dataset_names:
            warnings.warn(
                f"Relationship '{rel_name}': 'to' dataset '{to_ds}' is not "
                f"defined in the model"
            )

        from_cols = rel.get("from_columns", [])
        to_cols = rel.get("to_columns", [])
        if len(from_cols) != len(to_cols):
            raise OsiConversionError(
                f"Relationship '{rel_name}': from_columns and to_columns must "
                f"have the same length (got {len(from_cols)} and {len(to_cols)})"
            )
        if not from_cols:
            raise OsiConversionError(
                f"Relationship '{rel_name}': at least one column pair is required"
            )

        predicates = [
            f"${{{from_ds}.{fc}}} = ${{{to_ds}.{tc}}}"
            for fc, tc in zip(from_cols, to_cols)
        ]
        sql_on = " AND ".join(predicates)

        join_lines = [f"join: {to_ds} {{"]
        join_lines.append(_indent("type: left_outer", 1))
        join_lines.append(_indent("relationship: many_to_one", 1))
        join_lines.append(_indent(f"sql_on: {sql_on} ;;", 1))
        join_lines.append("}")
        by_base.setdefault(from_ds, []).append("\n".join(join_lines))

        if rel.get("ai_context"):
            warnings.warn(
                f"Relationship '{rel_name}': ai_context has no LookML join "
                f"equivalent and was dropped"
            )

    explore_blocks = []
    for base, joins in by_base.items():
        lines = [f"explore: {base} {{"]
        for j in joins:
            lines.append(_indent(j, 1))
            lines.append("")
        while len(lines) > 1 and lines[-1] == "":
            lines.pop()
        lines.append("}")
        explore_blocks.append("\n".join(lines))

    return "\n\n".join(explore_blocks)


def _convert_source(source, dataset_name):
    """Builds the LookML table clause from an OSI `source`.

    Returns a `sql_table_name: ... ;;` line for table references (backtick-
    quoting a 3-part BigQuery `project.dataset.table`), or a `derived_table`
    block for subquery sources. Returns None when source is empty.
    """
    if not source:
        warnings.warn(
            f"Dataset '{dataset_name}': no source provided; sql_table_name omitted"
        )
        return None

    source_stripped = str(source).strip()
    if not source_stripped:
        return None

    upper = source_stripped.upper()
    if upper.startswith(("SELECT ", "SELECT\n", "SELECT\t",
                         "WITH ", "WITH\n", "WITH\t")):
        return (
            "derived_table: {\n"
            + _indent(f"sql: {source_stripped} ;;", 1)
            + "\n}"
        )

    parts = source_stripped.split(".")
    if len(parts) == 3:
        # BigQuery fully-qualified names are conventionally backtick-quoted.
        return f"sql_table_name: `{source_stripped}` ;;"

    # Fall back to emitting the reference as-is rather than failing; Looker can
    # resolve 1- or 2-part names against the connection's default project.
    return f"sql_table_name: {source_stripped} ;;"


def _to_lookml_sql(expr, field_name):
    """Renders an OSI field expression as LookML `sql`.

    Bare identifiers are qualified as ${TABLE}.<identifier>. Computed
    expressions are emitted verbatim (a warning is raised so the author can
    confirm column qualification).
    """
    expr_stripped = expr.strip()
    if _SIMPLE_IDENTIFIER.match(expr_stripped):
        return f"${{TABLE}}.{expr_stripped}"
    warnings.warn(
        f"Field '{field_name}': computed expression emitted verbatim; verify "
        f"column qualification in LookML"
    )
    return expr_stripped


def _extract_expression(expression, name):
    """Selects the best dialect expression for BigQuery/LookML.

    Prefers BIGQUERY, falls back to ANSI_SQL. Returns the expression string, or
    None if only unsupported dialects are present (caller skips the entry).
    Raises OsiConversionError if the expression block is missing entirely.
    """
    if expression is None or not isinstance(expression, dict):
        raise OsiConversionError(
            f"Missing or malformed expression for field/metric '{name}'"
        )

    dialects = expression.get("dialects")
    if not dialects:
        raise OsiConversionError(f"Missing expression for field/metric '{name}'")

    bigquery_expr = None
    ansi_expr = None
    for d in dialects:
        dialect_name = (d.get("dialect") or "").upper()
        if dialect_name == "BIGQUERY":
            bigquery_expr = d.get("expression")
        elif dialect_name == "ANSI_SQL":
            ansi_expr = d.get("expression")

    if bigquery_expr is not None:
        return bigquery_expr
    if ansi_expr is not None:
        return ansi_expr

    dialect_names = [d.get("dialect", "") for d in dialects]
    warnings.warn(
        f"Skipping field/metric '{name}': no BigQuery-compatible expression "
        f"(has dialects: {', '.join(dialect_names)}; requires BIGQUERY or ANSI_SQL)"
    )
    return None


def _is_time_dimension(field):
    """Returns True when the field is marked as a time dimension."""
    dimension = field.get("dimension")
    return isinstance(dimension, dict) and dimension.get("is_time") is True


def _strip_time_suffix(name):
    """LookML convention: a dimension_group named `created` exposes
    `created_date`, `created_month`, etc. Strip a trailing `_date`/`_time` so
    the generated timeframes don't read as `created_date_date`."""
    for suffix in ("_date", "_time", "_datetime", "_timestamp"):
        if name.endswith(suffix) and len(name) > len(suffix):
            return name[: -len(suffix)]
    return name


def _entity_description(entity):
    """Builds a description string from `description` plus any `ai_context`
    synonyms, mirroring the Snowflake converter's behavior."""
    description = entity.get("description") or ""
    ai_context = entity.get("ai_context")
    if isinstance(ai_context, str) and ai_context:
        description = f"{description} {ai_context}".strip()
    elif isinstance(ai_context, dict):
        synonyms = ai_context.get("synonyms")
        if isinstance(synonyms, list) and synonyms:
            joined = ", ".join(str(s) for s in synonyms)
            description = (
                f"{description} (synonyms: {joined})".strip()
                if description
                else f"synonyms: {joined}"
            )
    return description


def _escape(text):
    """Escapes a string for a double-quoted LookML value."""
    return str(text).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def _indent(text, levels):
    """Indents every line of `text` by `levels` * 2 spaces."""
    pad = "  " * levels
    return "\n".join(pad + line if line else line for line in text.splitlines())


def _warn_dropped_fields(source, context):
    """Warns about OSI fields that have no LookML counterpart and are dropped."""
    dropped = []
    if source.get("custom_extensions"):
        dropped.append("custom_extensions")
    if source.get("version"):
        dropped.append("version")
    if source.get("label"):
        dropped.append("label")
    if dropped:
        warnings.warn(
            f"Dropped from {context} (no LookML counterpart): "
            + ", ".join(dropped)
        )


def main():
    parser = argparse.ArgumentParser(
        description="Convert Ossie YAML semantic model to LookML (Looker / BigQuery)"
    )
    parser.add_argument(
        "-i", "--input", required=True, help="Path to the Ossie YAML input file"
    )
    parser.add_argument(
        "-o", "--output", required=True, help="Path to write the LookML output"
    )
    args = parser.parse_args()

    with open(args.input, "r") as f:
        osi_yaml_str = f.read()

    try:
        lookml_str = convert_osi_to_lookml(osi_yaml_str)
    except OsiConversionError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    with open(args.output, "w") as f:
        f.write(lookml_str)

    print(f"Converted {args.input} -> {args.output}")


if __name__ == "__main__":
    main()
