# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""semantido v0.4/v0.5 surface — concept bindings, the concept registry
(with grain), and unique keys — carried into the Ossie document and
regenerated by the reverse direction."""

import json

from sqlalchemy import Column, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.orm import DeclarativeBase

from semantido import ConceptRegistry, SemanticBase, semantic_table
from ossie_semantido.constants import VENDOR_NAME
from ossie_semantido.ossie_to_semantido import ossie_to_semantido_source
from ossie_semantido.semantido_to_ossie import semantic_layer_to_ossie


class _Base(SemanticBase, DeclarativeBase):
    """Isolated base so this module does not pollute the shared registry."""


def _registry() -> ConceptRegistry:
    registry = ConceptRegistry(namespace="secmaster")
    isin = registry.concept("isin", "Issue-level instrument identifier.", grain="issue")
    registry.concept(
        "figi",
        "Listing-level instrument identifier.",
        grain="listing",
        distinct_from=isin,
    )
    return registry


@semantic_table(
    description="One row per security issue.",
    application_context="Golden record; downstream systems read only.",
    concept="isin",
)
class Security(_Base):
    __tablename__ = "security_master"

    id = Column(Integer, primary_key=True)
    primary_isin = Column(String(12))
    primary_isin_concept = "isin"
    figi = Column(String(12))
    figi_concept = "figi"

    __table_args__ = (UniqueConstraint("primary_isin"),)


@semantic_table(description="Vendor feed rows.")
class Feed(_Base):
    __tablename__ = "bbg_feed"

    id = Column(Integer, primary_key=True)
    security_id = Column(Integer, ForeignKey("security_master.id"))


def _payload(entity) -> dict:
    for ext in entity.custom_extensions or []:
        if ext.vendor_name == VENDOR_NAME:
            return json.loads(ext.data)
    return {}


def _document():
    layer = _Base.sync_semantic_layer(concept_registry=_registry())
    return semantic_layer_to_ossie(layer, model_name="secmaster").output


def test_forward_carries_v05_fields():
    document = _document()
    model = document.semantic_model[0]

    model_payload = _payload(model)
    registry = model_payload["concept_registry"]
    assert registry["namespace"] == "secmaster"
    assert registry["concepts"]["isin"]["grain"] == "issue"
    assert {
        (r["relation"], r["concept"]) for r in registry["concepts"]["figi"]["relations"]
    } == {("distinct_from", "isin")}

    datasets = {d.name: d for d in model.datasets}
    table_payload = _payload(datasets["security_master"])
    assert table_payload["concept"] == "isin"
    assert table_payload["unique_keys"] == [["primary_isin"]]
    assert table_payload["application_context"].startswith("Golden record")

    fields = {f.name: f for f in datasets["security_master"].fields}
    assert _payload(fields["primary_isin"])["concept"] == "isin"
    assert _payload(fields["figi"])["concept"] == "figi"


def test_reverse_regenerates_v05_authoring_surface():
    result = ossie_to_semantido_source(_document())
    source = result.output

    assert "concept='isin'," in source
    assert "primary_isin_concept = 'isin'" in source
    assert "figi_concept = 'figi'" in source
    assert "UniqueConstraint('primary_isin')" in source
    assert "application_context=" in source
    assert 'ForeignKey("security_master.id")' in source
    assert "grain='issue'" in source
    assert "distinct_from=" in source
    assert "CONCEPT_REGISTRY = build_registry()" in source
    assert "definition_checksum" not in source
    assert not result.issues


def test_generated_module_executes_and_resyncs():
    source = ossie_to_semantido_source(_document()).output
    # The generated module declares against the shared
    # SemanticDeclarativeBase; execute in isolation and re-sync.
    namespace: dict = {}
    exec(compile(source, "<generated>", "exec"), namespace)  # noqa: S102

    base = namespace["SemanticDeclarativeBase"]
    layer = base.sync_semantic_layer(concept_registry=namespace["CONCEPT_REGISTRY"])

    table = layer.tables["security_master"]
    assert table.concept == "isin"
    assert table.unique_keys == [["primary_isin"]]
    assert {c.name: c.concept for c in table.columns}["primary_isin"] == "isin"
    assert layer.concept_registry.concepts["figi"].grain == "listing"
